CM-1037: Support EID translation for TDD id in v7
LiveIntent/Prebid.js pull request #32
Opened 2023-12-14 19:26 UTC by wi101

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2023-12-15 09:22 UTC, 3link commented on modules/liveIntentIdSystem.js
> +
I submitted a PR to also expose the ext.provider in v7 now: https://github.com/prebid/Prebid.js/pull/10843/files#diff-489289275f4ee5264024b54c9c851e6c57684fd2d0bccab91d8b9ccef150e235R198. We should do it here too.

2023-12-15 09:24 UTC, 3link commented on test/spec/modules/liveIntentIdSystem_spec.js
> +
What about the `test/spec/modules/liveIntentIdMinimalSystem_spec.js`?

2023-12-15 09:24 UTC, 3link requested changes
Please see comments.

2023-12-15 12:01 UTC, 3link approved these changes

2023-12-21 15:07 UTC, peixunzhang approved these changes

2024-02-20 09:27 UTC, wi101 commented
This change is unnecessary as the v7 won't be released anymore

2024-02-20 09:27 UTC, closed without merging